#!/bin/sh /etc/rc.common

device=$(uci get xunlei.config.device)
file=$(uci get xunlei.config.file)
mountpoint="`mount | grep "$device" | awk '{print $3;exit}'`"
DIR=$file/xunlei
$DIR/portal -s
sleep 1
mkdir -p ${DIR}/cfg
cd ${DIR}
FILES=$(uci get xunlei.config.xware)
VERSION=`wget -qO- http://dl.lazyzhu.com/file/Thunder/Xware/latest`
ver=$(uci get xunlei.config.ver)
zversion=$(uci get xunlei.config.zversion)

{
	if [ "$zversion" -eq 1 ];then
        wget http://dl.lazyzhu.com/file/Thunder/Xware/${ver}/${FILES}
	else
        wget http://dl.lazyzhu.com/file/Thunder/Xware/${VERSION}/${FILES}
	fi
	}

rm -rf $DIR/portal && rm -rf $DIR/lib && tar zxvf ${FILES}
chmod +x $DIR/* && chmod +x $DIR/lib/*
rm -rf ${FILES}
rm -rf $file/xunlei/cfg/thunder_mounts.cfg>> /dev/null 2>&1
uci set xunlei.config.up=0>> /dev/null 2>&1
uci commit 2>&1 > /dev/null
vod=$(uci get xunlei.config.vod)   
[ "$vod" -eq 1 ] && rm -f "$file"/xunlei/vod_httpserver
[ "$vod" -eq 1 ] && rm -f "$file"/xunlei/lib/vod_httpserver

